name: Build with Nuitka

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest  # Nuitka builds best on Windows if your .bat expects it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust to your version

      - name: Install Nuitka and dependencies
        run: |
          pip install --upgrade pip
          pip install nuitka
          # Add any other dependencies your build script requires
          # e.g., pip install -r requirements.txt

      - name: Run build script
        run: |
          build_nuitka.bat
